builds:
  - main: ./
    binary: butterfish
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.BuildVersion={{.Tag}} -X main.BuildArch={{.Arch}} -X main.BuildCommit={{.ShortCommit}} -X main.BuildTimestamp={{.Date}} -X main.BuildOs={{.Os}}


release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: butterfish
    homepage: "https://github.com/bakks/butterfish"
    license: "MIT"
    description: "A tool for using LLMs on the command line"
    tap:
      owner: bakks
      name: homebrew-bakks
    commit_author:
      name: bakks
      email: pbbakkum@gmail.com

checksum:
  name_template: 'checksums.txt'
